# jekyll configuration

title: 'Welcome to the libremesh project'

exclude: [ 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README', 'vendor' ]

prefix: '/'

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks!

asciidoc_ext: txt

# end of configuration
